/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brandoncarvalho.sqlite.databases.project;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brandoncarvalho
 */
public class AccidentWindow extends javax.swing.JFrame {
    
    Connection con = null;
    
    /**
     * Creates new form AccidentWindow
     */
    public AccidentWindow() {
        initComponents();
        con = ConnectionToDB.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AA_DateField = new javax.swing.JTextField();
        AA_CityField = new javax.swing.JTextField();
        AA_StateField = new javax.swing.JTextField();
        numVehiclesInvolved = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vinsTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        damagesTextField = new javax.swing.JTextField();
        driverssnTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddAccidentBTN = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        accidentID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SA_AccidentInformationTable = new javax.swing.JTable();
        SearchSpecificAccident = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SA_VehicleInformationTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        SA_DateFrom = new javax.swing.JTextField();
        SA_DateTo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SA_AvgDamageFrom = new javax.swing.JTextField();
        SA_AvgDamageTo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SA_TotalDamageFrom = new javax.swing.JTextField();
        SA_TotalDamageTo = new javax.swing.JTextField();
        SearchFilteredAccidentsBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        SA_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Add Accident to Table");

        jLabel6.setText("Date (MM-DD-YYYY):");

        jLabel7.setText("City:");

        jLabel8.setText("State:");

        AA_DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AA_DateFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("# Vehicles Involved:");

        jLabel10.setText("VIN(s):");

        jLabel11.setText("Damage(s):");

        driverssnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverssnTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Driver_ssn(s):");

        AddAccidentBTN.setText("Add Accident");
        AddAccidentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccidentBTNActionPerformed(evt);
            }
        });

        jLabel14.setText("Comma Deliniated");

        jLabel15.setText("Keep vehicles in same order");

        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AA_DateField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AA_CityField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AA_StateField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(numVehiclesInvolved, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(vinsTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(damagesTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(driverssnTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AddAccidentBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(AA_DateField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(AA_CityField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AA_StateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numVehiclesInvolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(damagesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(driverssnTextField)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(57, 57, 57)
                        .addComponent(vinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel15)))
                .addGap(19, 19, 19))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(AddAccidentBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(358, 358, 358))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AA_DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numVehiclesInvolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AA_CityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(vinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AA_StateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(damagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(58, 58, 58)
                .addComponent(AddAccidentBTN)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Accident", jDesktopPane1);

        accidentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidentIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Search Accident");

        jLabel2.setText("Accident ID:");

        SA_AccidentInformationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "aid", "City", "State", "Date"
            }
        ));
        jScrollPane1.setViewportView(SA_AccidentInformationTable);

        SearchSpecificAccident.setText("Search");
        SearchSpecificAccident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSpecificAccidentActionPerformed(evt);
            }
        });

        SA_VehicleInformationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VIN", "Damages", "Driver_SSN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SA_VehicleInformationTable);

        jLabel3.setText("Accident Information");

        jLabel4.setText("Vehicles Involved");

        jDesktopPane4.setLayer(accidentID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(SearchSpecificAccident, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accidentID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchSpecificAccident)
                .addGap(389, 389, 389))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accidentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchSpecificAccident)
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Accident", jDesktopPane4);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Filter Accidents");

        jLabel16.setText("Filter by Date");

        jLabel17.setText("Filter by Avg. Damages");

        jLabel18.setText("Filter by Total Damages");

        jLabel19.setText("From:");

        jLabel20.setText("To:");

        SA_DateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SA_DateFromActionPerformed(evt);
            }
        });

        SA_DateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SA_DateToActionPerformed(evt);
            }
        });

        jLabel21.setText("From:");

        jLabel22.setText("To:");

        jLabel23.setText("From:");

        jLabel24.setText("To:");

        SA_TotalDamageFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SA_TotalDamageFromActionPerformed(evt);
            }
        });

        SA_TotalDamageTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SA_TotalDamageToActionPerformed(evt);
            }
        });

        SearchFilteredAccidentsBTN.setText("Search Accidents");
        SearchFilteredAccidentsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFilteredAccidentsBTNActionPerformed(evt);
            }
        });

        SA_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "aid", "Date", "City", "State"
            }
        ));
        jScrollPane3.setViewportView(SA_Table);

        jDesktopPane3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_DateFrom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_DateTo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_AvgDamageFrom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_AvgDamageTo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_TotalDamageFrom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SA_TotalDamageTo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(SearchFilteredAccidentsBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SA_DateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(SA_DateTo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(6, 6, 6))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)))
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(166, 166, 166)
                                .addComponent(jLabel18))
                            .addComponent(jLabel13)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SA_AvgDamageFrom)
                                    .addComponent(SA_AvgDamageTo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addGap(128, 128, 128)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(28, 28, 28)
                                        .addComponent(SA_TotalDamageTo))
                                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SA_TotalDamageFrom))))))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SearchFilteredAccidentsBTN)
                        .addGap(315, 315, 315)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(SA_DateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(SA_AvgDamageFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(SA_TotalDamageFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(SA_DateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(SA_AvgDamageTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(SA_TotalDamageTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchFilteredAccidentsBTN)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search all accidents", jDesktopPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Add Accident");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accidentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accidentIDActionPerformed

    private void SearchSpecificAccidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSpecificAccidentActionPerformed
        // TODO add your handling code here:
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try{
            String searchAccident;
            if(accidentID == null){
                searchAccident = "SELECT *" + "FROM accidents";
            }else{
                searchAccident = "SELECT * " + "FROM accidents " + "WHERE aid = " + accidentID.getText();
            }
            stmt = con.prepareStatement(searchAccident);
            stmt.clearParameters();
            rs = stmt.executeQuery();
            
            Object[] dataRow = new Object[4];
            DefaultTableModel accidentModel = (DefaultTableModel) SA_AccidentInformationTable.getModel();
            accidentModel.setRowCount(0);
            while(rs.next()){
                dataRow[0] = rs.getInt("aid");
                dataRow[1] = rs.getString("city");
                dataRow[2] = rs.getString("state");
                dataRow[3] = rs.getString("accident_date");
                accidentModel.addRow(dataRow);
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
        try{
            String involvedVehicles = "SELECT *" + "FROM involvements " + "WHERE aid = " + accidentID.getText();
            stmt = con.prepareStatement(involvedVehicles);
            stmt.clearParameters();
            rs = stmt.executeQuery();
            
            Object[] dataRow = new Object[3];
            DefaultTableModel involvementModel = (DefaultTableModel) SA_VehicleInformationTable.getModel();
            involvementModel.setRowCount(0);
            while(rs.next()){
                dataRow[0] = rs.getString("vin");
                dataRow[1] = rs.getString("damages");
                dataRow[2] = rs.getString("driver_ssn");
                involvementModel.addRow(dataRow);
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_SearchSpecificAccidentActionPerformed

    private void AA_DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AA_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AA_DateFieldActionPerformed

    private void driverssnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverssnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverssnTextFieldActionPerformed

    private void AddAccidentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccidentBTNActionPerformed
        // TODO add your handling code here:
        
        int latestID = 0;
        int numVehicles = (int)numVehiclesInvolved.getValue();
        PreparedStatement stmt;
        ResultSet rs;
        try{
            String getAIDQuery = "SELECT * FROM accidents";
            stmt = con.prepareStatement(getAIDQuery);
            rs = stmt.executeQuery();
            
            while(rs.next()){
                latestID = rs.getInt("aid");
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
        try{
            String addAccidentQuery = "INSERT INTO accidents " + "VALUES (?,?,?,?)";
            stmt = con.prepareStatement(addAccidentQuery);
            stmt.setInt(1,  latestID + 1);
            stmt.setString(2, AA_DateField.getText());
            stmt.setString(3, AA_CityField.getText());
            stmt.setString(4, AA_StateField.getText());
            stmt.executeUpdate();
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
        String[] vins = vinsTextField.getText().split(",");
        String[] damages = damagesTextField.getText().split(",");
        String[] driver_ssns = driverssnTextField.getText().split(",");
        
        try{
            for(int i = 0; i < numVehicles; i++){
                String addInvolvementQuery = "INSERT INTO involvements " + "VALUES (?,?,?,?)";
                stmt = con.prepareStatement(addInvolvementQuery);
                stmt.setInt(1, latestID + 1);
                stmt.setString(2, vins[i]);
                stmt.setString(3, damages[i]);
                stmt.setString(4, driver_ssns[i]);
                stmt.executeUpdate();
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_AddAccidentBTNActionPerformed

    private void SA_DateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SA_DateFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SA_DateFromActionPerformed

    private void SA_DateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SA_DateToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SA_DateToActionPerformed

    private void SA_TotalDamageFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SA_TotalDamageFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SA_TotalDamageFromActionPerformed

    private void SA_TotalDamageToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SA_TotalDamageToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SA_TotalDamageToActionPerformed

    private void SearchFilteredAccidentsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFilteredAccidentsBTNActionPerformed
        // TODO add your handling code here:
        PreparedStatement stmt = null;
        ResultSet rs;
        String query =  "SELECT * FROM accidents";
        
        DefaultTableModel accidentModel = (DefaultTableModel) SA_Table.getModel();
        Object[] dataRow = new Object[4];
        accidentModel.setRowCount(0);

        try{
            if(!SA_DateFrom.getText().isEmpty() && !SA_AvgDamageFrom.getText().isEmpty() && !SA_TotalDamageFrom.getText().isEmpty()){
                
            }else if(!SA_DateFrom.getText().isEmpty() && !SA_AvgDamageFrom.getText().isEmpty()){
                
            }else if(!SA_AvgDamageFrom.getText().isEmpty() && !SA_TotalDamageFrom.getText().isEmpty()){
                
            }else if(!SA_DateFrom.getText().isEmpty() && !SA_TotalDamageFrom.getText().isEmpty()){
                
            }else if(!SA_DateFrom.getText().isEmpty()){
                query = "SELECT * FROM accidents WHERE accident_date BETWEEN '" + SA_DateFrom.getText() + "' AND '" + SA_DateTo.getText() + "'"; // COmplete
            }else if(!SA_AvgDamageFrom.getText().isEmpty()){
                
            }else if(!SA_TotalDamageFrom.getText().isEmpty()){
                query = "SELECT * FROM accidents WHERE aid IS IN (SELECT aid FROM involvments WHERE damages >= " + SA_TotalDamageFrom.getText() + " AND damages <= " + SA_TotalDamageTo.getText();
            }
            
            System.out.println(query);
            stmt = con.prepareStatement(query);
            rs = stmt.executeQuery();
            
            while(rs.next()){
                dataRow[0] = rs.getString("aid");
                dataRow[1] = rs.getString("accident_date");
                dataRow[2] = rs.getString("city");
                dataRow[3] = rs.getString("state");
                accidentModel.addRow(dataRow);
            }
            
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_SearchFilteredAccidentsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccidentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccidentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccidentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccidentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccidentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AA_CityField;
    private javax.swing.JTextField AA_DateField;
    private javax.swing.JTextField AA_StateField;
    private javax.swing.JButton AddAccidentBTN;
    private javax.swing.JTable SA_AccidentInformationTable;
    private javax.swing.JTextField SA_AvgDamageFrom;
    private javax.swing.JTextField SA_AvgDamageTo;
    private javax.swing.JTextField SA_DateFrom;
    private javax.swing.JTextField SA_DateTo;
    private javax.swing.JTable SA_Table;
    private javax.swing.JTextField SA_TotalDamageFrom;
    private javax.swing.JTextField SA_TotalDamageTo;
    private javax.swing.JTable SA_VehicleInformationTable;
    private javax.swing.JButton SearchFilteredAccidentsBTN;
    private javax.swing.JButton SearchSpecificAccident;
    private javax.swing.JTextField accidentID;
    private javax.swing.JTextField damagesTextField;
    private javax.swing.JTextField driverssnTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner numVehiclesInvolved;
    private javax.swing.JTextField vinsTextField;
    // End of variables declaration//GEN-END:variables
}
